# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.player_display.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_display', 'function_path': 'animated_java:player_display/animations/knockback_on_air/stop'}
tag @s remove aj.player_display.animation.knockback_on_air.playing
scoreboard players set @s aj.knockback_on_air.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:player_display/animations/knockback_on_air/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only