# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:player_display/animations/knockback_on_air/zzz/apply_frame {frame: 121}
scoreboard players add @s aj.knockback_on_air.frame 1