# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute if score @s aj.knockback_on_air.frame matches -1 run function animated_java:player_display/animations/knockback_on_air/zzz/commands_keyframe_loop_patch
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.knockback_on_air.frame
function animated_java:player_display/animations/knockback_on_air/zzz/apply_frame with storage aj:temp args
execute if score @s aj.knockback_on_air.frame matches 120.. run return run scoreboard players set @s aj.knockback_on_air.frame -1
scoreboard players add @s aj.knockback_on_air.frame 1