# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.knockback_on_air.frame dummy
scoreboard objectives add aj.knockback_on_ground.frame dummy